### ISSUE TITLE
release版本城市选择器崩溃了

### ISSUE THREAD

**Issue by LuoGuoXin** [li-xiaojun/XPopupExt#23]
debug下没问题，release下，城市选择器崩溃了。是哪里需要混淆吗？
Back traces starts.
java.lang.NullPointerException
	at com.lxj.xpopupext.popup.CityPickerPopup.j(:35)
	at com.lxj.xpopup.core.BasePopupView.m(:7)

**Comment by LuoGuoXin** [comment]
-keep class com.lxj.xpopupext.bean.** { <fields>; }
这个混淆

**Comment by junixapp** [comment]
-keep class com.lxj.xpopupext.bean.** { ; }
