### ISSUE TITLE
城市选择器划快一点会越界

### ISSUE THREAD

**Issue by ChanKingBooo** [li-xiaojun/XPopupExt#3]
在省份、城市、区域一直划，划快点会崩
![image](https://user-images.githubusercontent.com/11921548/86547379-67142200-bf6b-11ea-9021-5929630f61c2.png)

**Comment by naixiu007** [comment]
同样遇到这个问题，作者有时间还是修复一下吧
![image](https://user-images.githubusercontent.com/20724378/102293268-b4b4a200-3f81-11eb-9dab-34576b62d6c7.png)

**Comment by caopu0707** [comment]
同样遇到这个问题，作者有时间还是修复一下吧

**Comment by junixapp** [comment]
@ChanKingBooo  @caopu0707 
0.0.4已修复
