### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by BugRui** [li-xiaojun/XPopupExt#7]
//popup弹窗
    implementation 'com.lxj:xpopup:2.2.10'
    implementation 'com.lxj:xpopup-ext:0.0.3'

```

XPopup.Builder(this)
        .hasShadowBg(true)
        .autoFocusEditText(false)
        .popupPosition(PopupPosition.Bottom)
        .asCustom(TimePickerPopup(this@createTimePickerPopup)
            .setMode(mode)
            .setDefaultDate(todayCalendar)  //设置默认选中日期
            .setYearRange(
                2000,
                Calendar.getInstance().get(Calendar.YEAR) + 10
            ) //设置年份范围
            .setDateRang(startCalendar, endCalendar) //设置日期范围
            .setTimePickerListener(object : TimePickerListener {
                override fun onTimeChanged(date: Date?) {
                    //时间改变
                }

                override fun onTimeConfirm(date: Date, view: View?) {
                    //点击确认时间
                    itemClick(date)
                }
            })
        )
        .show()


```

java.lang.StackOverflowError
stack size 8MB
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)
com.contrarywind.view.WheelView.OooO0OO(WheelView.java:2)

**Comment by junixapp** [comment]
更新到0.0.4即可
